### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by quangas** [heroiclabs/nakama-project-template#13]
When trying to run

docker-compose up --build nakama

=> ERROR [builder 4/4] RUN go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so                                                                                                                                                                           

------
 > [builder 4/4] RUN go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so:
#9 0.266 go: cannot find main module, but found .git/config in /backend
#9 0.266 	to create a module there, run:
#9 0.266 	go mod init
------
executor failed running [/bin/sh -c go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so]: exit code: 1

**Comment by zyro** [comment]
@quangas I've just tried it and it builds fine on current master (26b890af580dcde3fd33374c634ae592d301908f).

Try running `docker-compose down -v`, then run `docker-compose up --build nakama` again. Also double-check you're running this command at the root of the repo.

Have you made any changes to the code, config, or supporting files?

**Comment by quangas** [comment]
Thanks @zyro 

I updated my docker desktop just in case it was old and it seemed to work now.
