### ISSUE TITLE
Issue transpiling typesript

### ISSUE THREAD

**Issue by growthdyn-luke** [heroiclabs/nakama-project-template#15]
I am attempting to set up the project as instructed in this tutorial: https://heroiclabs.com/docs/nakama/tutorials/js/xoxo/
However, while running the command `npx tsc` I am running into this error:

`match_handler.ts:275:41 - error TS2339: Property 'binaryToString' does not exist on type 'Nakama'.`
`275                     msg = JSON.parse(nk.binaryToString(message.data));`
`                                            ~~~~~~~~~~~~~~`
Looking at the file match_handler.ts VS code shows that nkruntime.Nakama does not have the function binaryToString defined.

I'm not sure what I'm missing but would appreciate any help you can provide.

**Comment by novabyte** [comment]
@growthdyn-luke It looks like the project template still uses the v1.20.0 version of the Nakama Type definitions. I'll update it but in the meantime you can upgrade the dependency in your `package.json` to use v1.21.0 release:

https://github.com/heroiclabs/nakama-project-template/blob/master/package.json#L23

Make sure to run `npm upgrade` afterwards IIRC.

**Comment by novabyte** [comment]
@growthdyn-luke I updated the package JSON to use the latest Type definitions and re-ran `npx tsc` to execute the TypeScript compiler on the codebase and it all worked. Let me know if your problem persists but in the meantime I'll close this issue. Thanks for reporting it 🙏

**Comment by growthdyn-luke** [comment]
Thank you for your quick reply! that worked beautifully.
