### ISSUE TITLE
Missing package.json file

### ISSUE THREAD

**Issue by attackgoat** [heroiclabs/nakama-project-template#8]
Until this is resolved the correct dependencies can [be found here](https://heroiclabs.com/docs/runtime-code-typescript-setup/).

**Comment by novabyte** [comment]
Thanks @attackgoat. I think the file was excluded by the ignore file but is resolved in https://github.com/heroiclabs/nakama-project-template/commit/9e2a5a7d8104b41df6bd357dc049d4bce54a1eab.
